#!/usr/bin/env bash
set -euo pipefail

# Download anonymous SRA links for PRJNA531644
# Generated by run_get_bioinfor_from_NCBI_SRA.py

# filename: chow1_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./chow1_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869105/chow1_possorted_genome_bam.bam.1 ./

# filename: SRR8869105; semantic_name: SRA Normalized
[[ -f ./SRR8869105 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869105/SRR8869105 ./

# filename: chow3_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./chow3_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869107/chow3_possorted_genome_bam.bam.1 ./

# filename: SRR8869107; semantic_name: SRA Normalized
[[ -f ./SRR8869107 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869107/SRR8869107 ./

# filename: nash1_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./nash1_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869108/nash1_possorted_genome_bam.bam.1 ./

# filename: SRR8869108; semantic_name: SRA Normalized
[[ -f ./SRR8869108 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869108/SRR8869108 ./

# filename: nash2_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./nash2_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869109/nash2_possorted_genome_bam.bam.1 ./

# filename: SRR8869109; semantic_name: SRA Normalized
[[ -f ./SRR8869109 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869109/SRR8869109 ./

# filename: nash3_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./nash3_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869110/nash3_possorted_genome_bam.bam.1 ./

# filename: SRR8869110; semantic_name: SRA Normalized
[[ -f ./SRR8869110 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869110/SRR8869110 ./

# filename: SRR9054070; semantic_name: SRA Normalized
[[ -f ./SRR9054070 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR9054070/SRR9054070 ./

