#!/usr/bin/env bash
set -euo pipefail

# Download anonymous SRA links for SRR8869105
# Generated by run_get_bioinfor_from_NCBI_SRA.py

# filename: chow1_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
wget -c -O chow1_possorted_genome_bam.bam https://sra-pub-src-1.s3.amazonaws.com/SRR8869105/chow1_possorted_genome_bam.bam.1

# filename: SRR8869105; semantic_name: SRA Normalized
wget -c -O SRR8869105 https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR8869105/SRR8869105

# filename: SRR8869105.sralite; semantic_name: SRA Lite
wget -c -O SRR8869105.sralite https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos9/sra-pub-zq-922/SRR008/869/SRR8869105.sralite.1

