#!/usr/bin/env bash
set -euo pipefail

# Download anonymous SRA links for SRR8869108
# Generated by run_get_bioinfor_from_NCBI_SRA.py

# filename: nash1_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./nash1_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869108/nash1_possorted_genome_bam.bam.1 ./

# filename: SRR8869108; semantic_name: SRA Normalized
[[ -f ./SRR8869108 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869108/SRR8869108 ./

