#!/usr/bin/env bash
set -euo pipefail

# Download anonymous SRA links for SRR8869107
# Generated by run_get_bioinfor_from_NCBI_SRA.py

# filename: chow3_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
[[ -f ./chow3_possorted_genome_bam.bam.1 ]] || aws s3 cp --no-sign-request s3://sra-pub-src-1/SRR8869107/chow3_possorted_genome_bam.bam.1 ./

# filename: SRR8869107; semantic_name: SRA Normalized
[[ -f ./SRR8869107 ]] || aws s3 cp --no-sign-request s3://sra-pub-run-odp/sra/SRR8869107/SRR8869107 ./

