#!/usr/bin/env bash
set -euo pipefail

# Download anonymous SRA links for SRR8869109
# Generated by run_get_bioinfor_from_NCBI_SRA.py

# filename: nash2_possorted_genome_bam.bam; semantic_name: 10X Genomics bam file
wget -c -O nash2_possorted_genome_bam.bam https://sra-pub-src-1.s3.amazonaws.com/SRR8869109/nash2_possorted_genome_bam.bam.1

# filename: SRR8869109; semantic_name: SRA Normalized
wget -c -O SRR8869109 https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR8869109/SRR8869109

# filename: SRR8869109.sralite; semantic_name: SRA Lite
wget -c -O SRR8869109.sralite https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR008/869/SRR8869109.sralite.1

