#!/usr/bin/env bash
set -euo pipefail

# Download anonymous SRA links for SRR9054070
# Generated by run_get_bioinfor_from_NCBI_SRA.py

# filename: SRR9054070; semantic_name: SRA Normalized
wget -c -O SRR9054070 https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR9054070/SRR9054070

# filename: SRR9054070.sralite; semantic_name: SRA Lite
wget -c -O SRR9054070.sralite https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos5/sra-pub-zq-14/SRR009/054/SRR9054070.sralite.1

